# ==========================================
# Papagaio Fly — Decision Tree API Route
# Serves the LLM-generated decision tree JSON
# ==========================================

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/api", tags=["decision-tree"])

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

@router.get("/decision-tree")
def get_decision_tree():
    """Return the full decision tree JSON generated by the Agentic Workflow."""
    tree_path = DATA_DIR / "decision_tree.json"
    if not tree_path.exists():
        raise HTTPException(status_code=404, detail="Decision tree not generated yet. Run generate_decision_tree.py first.")
    with open(tree_path, "r", encoding="utf-8") as f:
        return json.load(f)
